const assert = require("assert");
const fs = require("fs");

const css = fs.readFileSync("assets/css/style.css", "utf8");
const hangmanCss = fs.readFileSync("assets/projects/hangOut/style.css", "utf8");
const js = fs.readFileSync("assets/js/script.js", "utf8");
const html = fs.readFileSync("index.html", "utf8");

assert.ok(/\[hidden\]\s*\{[^}]*display:\s*none\s*!important/i.test(css), "hidden elements must override component display styles");
assert.ok(html.includes("data-experience-older hidden"), "older experience entries should render with hidden attribute");
assert.ok(js.includes("item.hidden = expanded"), "experience toggle should hide entries again after collapse");
assert.ok(js.includes("window.open(button.dataset.printPdf"), "print action should open the PDF directly instead of printing a zero-size iframe");
assert.ok(!js.includes('frame.style.width = "0"'), "print action must not use a zero-width iframe");
assert.ok(/body\s*\{[^}]*overflow-x:\s*hidden/i.test(css), "page should prevent mobile horizontal overflow");
assert.ok(/body::before\s*\{[^}]*animation:\s*tvReveal\s+2200ms/i.test(css), "intro TV reveal should stay visible long enough to notice");
assert.ok(/\.audio-bubble\s*\{[^}]*position:\s*absolute/i.test(css), "audio bubble should not push the speaker button in layout");
assert.ok(/\.audio-toggle\s*\{[^}]*margin-top:\s*8px/i.test(css), "speaker button should sit slightly lower in the toolbar");
assert.ok(/@media\s*\(max-width:\s*640px\)[\s\S]*\.timeline-item\s*\{[^}]*grid-template-columns:\s*1fr/i.test(css), "timeline should collapse to one column on phones");
assert.ok(/#alphabet\s*\{[^}]*display:\s*grid/i.test(hangmanCss), "hangman alphabet should use a stable grid");
assert.ok(/\.letter\s*\{[^}]*display:\s*flex/i.test(hangmanCss), "hangman letters should center glyphs with flex");
assert.ok(!/\.letter\s*\{[^}]*float:\s*left/i.test(hangmanCss), "hangman letters should not rely on floats");
assert.ok(html.includes("data-developer-toggle"), "page should expose developer mode toggle");
assert.ok(html.includes("data-terminal-status"), "page should render the terminal status bar");
assert.ok(html.includes("data-skill-filter"), "skills should be interactive filters");
assert.ok(!html.includes("data-project-track"), "projects should not use a horizontal carousel track");
assert.ok(!html.includes("data-project-scroll"), "project section should not render carousel controls");
assert.ok(html.includes("assets/projects/domkiDemo/index.html"), "projects should include local Domki static demo");
assert.ok(html.includes("assets/projects/hurtowniaDemo/index.html"), "projects should include local Hurtownia static demo");
assert.ok(!html.includes("https://github.com/RufusCarlito/domki"), "Domki project should not link directly to repository");
assert.ok(!html.includes("https://github.com/RufusCarlito/hurtownia"), "Hurtownia project should not link directly to repository");
assert.ok(html.includes("data-weather-card"), "page should render a weather card");
assert.ok(html.includes("data-weather-forecast"), "weather card should expose a forecast container");
assert.ok(html.includes("data-theme-toggle"), "page should expose a day/night theme toggle");
assert.ok(html.includes("data-weather-range"), "weather card should show day/night temperature range");
assert.ok(html.includes("data-cookie-note"), "page should render the cookie note");
assert.ok(html.includes("data-cookie-dismiss"), "cookie note should include a dismiss action");
assert.ok(js.includes("function applySkillFilter"), "skill filtering should be handled in JavaScript");
assert.ok(html.includes('data-download-pl="assets/downloads/K.Romsicki_cv_pl.pdf"'), "download button should keep the Polish CV path");
assert.ok(html.includes('data-download-en="assets/downloads/K.Romsicki_cv_EN.pdf"'), "download button should expose the English CV path");
assert.ok(html.includes('data-print-en="assets/downloads/K.Romsicki_cv_EN.pdf"'), "print button should expose the English CV path");
assert.ok(js.includes("function syncCvActions"), "language switching should synchronize CV download actions");
assert.ok(js.includes("link.dataset[`download${language.charAt(0).toUpperCase()}${language.slice(1)}`]"), "download link should react to current language");
assert.ok(js.includes("button.dataset[`print${language.charAt(0).toUpperCase()}${language.slice(1)}`]"), "print action should react to current language");
assert.ok(js.includes('const cookieNoteStorageKey = "krystianCvCookieNoteDismissed"'), "cookie note should persist dismissal locally");
assert.ok(js.includes("function initCookieNote"), "cookie note should be initialized in JavaScript");
assert.ok(/\.cookie-note\s*\{[^}]*position:\s*fixed/i.test(css), "cookie note should float above the page layout");
assert.ok(/\.cookie-note__close\s*\{[^}]*border-radius:\s*999px/i.test(css), "cookie note CTA should stay pill-shaped");
assert.ok(!js.includes("setPointerCapture"), "project cards should not intercept pointer events");
assert.ok(!js.includes("didProjectDrag"), "project card clicks should not be blocked by drag state");
assert.ok(js.includes("IntersectionObserver"), "sections should reveal with scroll-aware animation");
assert.ok(js.includes("api.open-meteo.com/v1/forecast"), "weather should use the Open-Meteo forecast API");
assert.ok(js.includes("navigator.geolocation"), "weather should try user location before relying on fallback display");
assert.ok(js.includes("is_day"), "weather should account for day and night");
assert.ok(js.includes("sunrise,sunset"), "weather should request sunrise and sunset data");
assert.ok(js.includes("function getMoonPhase"), "weather should calculate moon phase for night display");

console.log("staticInteractionRules.test.js: OK");
